Add .clang-format and reformat
illiliti/libudev-zero pull request #37
Opened 2021-08-29 14:22 UTC by AGLExport

libudev-zero is not defined coding-style. This pull request add to coding-style information using clang-format.
This .clang-format is not match existing coding style completely.   When this pull request will apply, few code will change.

If libudev-zero define coding style, it will support code contribution.

2021-09-01 11:20 UTC, illiliti requested changes

2021-09-09 22:59 UTC, AGLExport commented on udev.c
> +                                                       const char *format, va_list args))
This review point was fixed. Please check 
https://github.com/illiliti/libudev-zero/pull/37/commits/54d3c47ec17ba5b44845835c8c8bd7892623f129
Other point is now working.

To fix this point, I set ColumnLimit 120 from unlimited. Is it OK?

2021-09-09 22:59 UTC, AGLExport commented on udev.h
> +                                                       const char *format, va_list args));
This review point was fixed. Please check 
https://github.com/illiliti/libudev-zero/pull/37/commits/54d3c47ec17ba5b44845835c8c8bd7892623f129
Other point is now working.

To fix this point, I set ColumnLimit 120 from unlimited. Is it OK?

2021-11-07 16:01 UTC, closed without merging

2021-11-07 16:02 UTC, AGLExport commented
This pull request rewrite at #46.